name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  get-tools:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - uses: actions/checkout@v3
      - run: |
          apt-get update
          apt-get install -y make

  build:
    runs-on: ubuntu-latest
    needs: get-tools
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - run: |
          apt-get update
          apt-get install -y make
      - run: make activate-scripts
      - run: make restore
      - run: make build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./bin/

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - run: |
          apt-get update
          apt-get install -y make
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./bin/
      - run: make activate-scripts
      - run: make test
#Deploy stage coming soon
